apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaddy-pvc-list-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["list", "get", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaddy-pvc-list-binding
subjects:
- kind: ServiceAccount
  name: kaddy-controller-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: kaddy-pvc-list-role
  apiGroup: rbac.authorization.k8s.io
